replicaCount: 3

image:
  repository: ghcr.io/your-org/agent360
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: agent360.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

cassandra:
  enabled: true
  persistence:
    size: 100Gi
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 4

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
  master:
    persistence:
      size: 10Gi

temporal:
  enabled: true
  server:
    replicaCount: 3
  cassandra:
    enabled: false
    external:
      enabled: true
      hosts:
        - cassandra-0.cassandra
        - cassandra-1.cassandra
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

config:
  environment: production
  logging:
    level: INFO
    format: json
  monitoring:
    prometheus:
      enabled: true
      port: 8000
  agent:
    maxConcurrentTasks: 100
    defaultTimeoutSeconds: 300
