[pytest]
asyncio_mode = strict
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    asyncio: mark test as async/await test
    integration: mark test as an integration test
    performance: mark test as a performance test

# Coverage settings
addopts = 
    --cov=src 
    --cov-report=term-missing 
    --cov-report=html 
    --cov-branch 
    --no-cov-on-fail

# Coverage configuration
[coverage:run]
branch = True
source = src

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self.debug:
    raise NotImplementedError
    if __name__ == .__main__.:
    pass
    raise ImportError

[coverage:html]
directory = coverage_html
