apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    istio-injection: enabled
    name: {{ .Release.Namespace }}
    environment: {{ .Values.environment }}
    security.istio.io/tlsMode: istio
