apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-redpanda-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redpanda
  endpoints:
    - port: admin
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-redpanda-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: redpanda.rules
      rules:
        - alert: RedpandaHighLatency
          expr: |
            histogram_quantile(0.95, sum(rate(redpanda_message_latency_seconds_bucket[5m])) by (le, topic)) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High message latency on Redpanda
            description: 95th percentile latency is above 1 second for topic {{ $labels.topic }}
        
        - alert: RedpandaConsumerLag
          expr: |
            sum(redpanda_consumer_group_lag) by (topic, consumer_group) > 1000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High consumer lag on Redpanda
            description: Consumer group {{ $labels.consumer_group }} is lagging by {{ $value }} messages on topic {{ $labels.topic }}
        
        - alert: RedpandaHighErrorRate
          expr: |
            sum(rate(redpanda_errors_total[5m])) by (type) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High error rate on Redpanda
            description: Error rate is above 0.1 errors/second for type {{ $labels.type }}
---
apiVersion: grafana.integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: {{ .Release.Name }}-redpanda
  namespace: {{ .Release.Namespace }}
spec:
  json: |
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "title": "Message Throughput",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "sum(rate(redpanda_messages_produced_total[5m])) by (topic)",
              "legendFormat": "{{topic}} - produced"
            },
            {
              "expr": "sum(rate(redpanda_messages_consumed_total[5m])) by (topic)",
              "legendFormat": "{{topic}} - consumed"
            }
          ]
        },
        {
          "title": "Message Latency",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "histogram_quantile(0.95, sum(rate(redpanda_message_latency_seconds_bucket[5m])) by (le, topic))",
              "legendFormat": "{{topic}} - p95"
            }
          ]
        },
        {
          "title": "Consumer Group Lag",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "sum(redpanda_consumer_group_lag) by (topic, consumer_group)",
              "legendFormat": "{{consumer_group}} - {{topic}}"
            }
          ]
        }
      ],
      "refresh": "10s",
      "schemaVersion": 16,
      "style": "dark",
      "tags": ["redpanda", "streaming"],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "browser",
      "title": "Redpanda Metrics",
      "version": 0
    }
