apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: agent360
data:
  alert-rules.yaml: |
    groups:
      - name: Agent360Alerts
        folder: Agent360 Alerts
        interval: 1m
        rules:
          - name: HighErrorRate
            condition: B
            data:
              - refId: A
                datasourceUid: prometheus
                model:
                  expr: rate(http_requests_total{status=~"5.*"}[5m]) / rate(http_requests_total[5m]) * 100
                  instant: false
                  range: true
                  refId: A
              - refId: B
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                  datasource:
                    name: Expression
                    type: __expr__
                  expression: A
                  hide: false
                  refId: B
                  type: math
            no_data_state: OK
            exec_err_state: Error
            for: 5m
            annotations:
              summary: High error rate detected
            labels:
              severity: warning

          - name: SlowResponseTime
            condition: B
            data:
              - refId: A
                datasourceUid: prometheus
                model:
                  expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])
                  instant: false
                  range: true
                  refId: A
              - refId: B
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                  datasource:
                    name: Expression
                    type: __expr__
                  expression: A
                  hide: false
                  refId: B
                  type: math
            no_data_state: OK
            exec_err_state: Error
            for: 5m
            annotations:
              summary: Slow response times detected
            labels:
              severity: warning
