blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/DSamuelHodge/agent360/wiki
    about: Check our documentation before creating an issue
  - name: Security Issue
    url: https://github.com/DSamuelHodge/agent360/security/policy
    about: Please report security vulnerabilities here
