global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'temporal'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['temporal:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: 'agent360'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent360:8081']

  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'cassandra'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cassandra-exporter:9500']
