apiVersion: v1
kind: Service
metadata:
  name: agent360
  namespace: agent360
  labels:
    app: agent360
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agent360
