apiVersion: v1
kind: ConfigMap
metadata:
  name: agent360-config
  namespace: agent360
data:
  environment: production
  cassandra_hosts: "cassandra-0.cassandra.agent360.svc.cluster.local,cassandra-1.cassandra.agent360.svc.cluster.local"
  redis_host: "redis-master.agent360.svc.cluster.local"
  temporal_host: "temporal.agent360.svc.cluster.local:7233"
  config.yaml: |
    logging:
      level: INFO
      format: json
    
    monitoring:
      prometheus:
        enabled: true
        port: 8000
      
    agent:
      max_concurrent_tasks: 100
      default_timeout_seconds: 300
      
    tools:
      rest_tool:
        timeout_seconds: 30
        max_retries: 3
      database_tool:
        connection_pool_size: 10
        max_connections: 100
      rag_tool:
        vector_dimension: 1536
        similarity_threshold: 0.7
