log:
  stdout: true
  level: info

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 1
  datastores:
    default:
      cassandra:
        hosts: ["cassandra"]
        keyspace: "temporal"
        user: ""
        password: ""
        port: 9042
        datacenter: "datacenter1"
        maxConns: 2
        connectTimeout: 5s
    visibility:
      cassandra:
        hosts: ["cassandra"]
        keyspace: "temporal_visibility"
        user: ""
        password: ""
        port: 9042
        datacenter: "datacenter1"
        maxConns: 2
        connectTimeout: 5s

global:
  membership:
    maxJoinDuration: 30s
  pprof:
    port: 7936
  metrics:
    prometheus:
      timerType: "histogram"
      listenAddress: "0.0.0.0:8000"

services:
  frontend:
    rpc:
      grpcPort: 7233
      bindOnIP: "0.0.0.0"
      membershipPort: 6933
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8000"

  matching:
    rpc:
      grpcPort: 7235
      bindOnIP: "0.0.0.0"
      membershipPort: 6935
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8000"

  history:
    rpc:
      grpcPort: 7234
      bindOnIP: "0.0.0.0"
      membershipPort: 6934
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8000"

  worker:
    rpc:
      grpcPort: 7239
      bindOnIP: "0.0.0.0"
      membershipPort: 6939
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8000"

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "temporal"
      rpcAddress: "0.0.0.0:7233"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  history:
    state: "disabled"
    enableRead: false
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "disabled"
    enableRead: false
